title: Quizzing App v2
theme: jekyll-theme-minimal
show_downloads: true
logo: https://raw.githubusercontent.com/GeetanshGautam0/cmf-qas/master/.icons/quizzing_tool.png
site_favicon: .icons/favicon.ico